[package]
name = "creature-simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["bevy_sprite", "bevy_render"] }
noise = "0.9"
rand = "0.8"
futures-lite = "2.0"
